### ISSUE TITLE
Dealing with global Polyfills better

### ISSUE THREAD

**Issue by kitsonk** [dojo/shim#106]
**Enhancement**

Maintaining external polyfills for the rest of Dojo 2 is becoming problematic.  While `shim` is great for stable functionality, where it is easy to author the polyfill, integrating 3rd party polyfills is becoming problematic, especially elided those polyfills from the built code when they are not needed on certain platforms.

Therefore we should develop a better solution, that preserves easy of use of Dojo 2 with an AMD loader, but allows the build to be optimised with webpack.

The enhancement has two parts:

* First, all of our imports of polyfills that are side-effect polyfills which put the code in the global namespace, to provide a standards based API should be imported in a single module.
* We would define a feature flag for each feature and indicate that feature flag in a pragma before the import.  This would allow us to build the capability in webpack to analyse statically asserted flags and elide the import from the build if appropriate.

For example, we would have a module named `@dojo/shim/main` which could contain something like the following:

```ts
"!has('es6-promise')";
import './Promise';

"!has('es6-symbol')";
import './Symbol';

"!has('dom-intersection-observer')";
import 'intersection-observer';
```

We would then ensure that this module gets loaded at least once when using an AMD loader.  We would also make changes to `cli-build-webpack` to be able to understand the pragma statements and elide the next import from the build.

We would expect all polyfills we incorporated to be "well behaved" in that they would only operate if the functionality was missing in the global namespace at runtime and they have the same API surface as the standard.

This is a **breaking change** because other packages would need to change the way they load at least the pepjs polyfill as well as no longer import the `@dojo/shim/Promise` and `@dojo/shim/Symbol` polyfills for side-effects.

**Comment by rorticus** [comment]
After chatting with @kitsonk and @matt-gadd, I think we're going to create a utility function that will mix in the polyfill config with an existing AMD config. Something like:

```html
<script src="./node_modules/@dojo/shim/util/amd.js"></script>
<script src="./node_modules/@dojo/loader/loader.js></script>
<script>
   require.config(ourUtilMixer(myNormalLoaderConfig));
</script>
```
