### ISSUE TITLE
Use of downlevelIteration

### ISSUE THREAD

**Issue by kitsonk** [dojo/shim#109]
**Enhancement**

We should consider using the compiler flag `downlevelIteration`.  Our Symbol shim should be sufficient to allow TypeScript to down emit `for ... of` structures on any iterators.  This means that we would not have to use the "iterator/forOf" function to replicate iteration and more widely adopt iterables throughout the code base (as well as allow downstream authoring with iterables).

**Comment by rorticus** [comment]
Added in https://github.com/dojo/shim/pull/114
