### ISSUE TITLE
Migrate from Task to cancellable Promise

### ISSUE THREAD

**Issue by kitsonk** [dojo/shim#16]
@kitsonk commented on [Fri Aug 12 2016](https://github.com/dojo/core/issues/183)

There is now a Stage 1 Proposal to [add cancelability to `Promise`](https://docs.google.com/presentation/d/1V4vmC54gJkwAss1nfEt9ywc-QOVOfleRxD5qtpMpc8U/edit#slide=id.gc6f9e470d_0_0).

We already adjust the native ES6 Promise a bit in `core`, but we could also adopt the functionality described in the proposal and hope that we can offload this in the future.

This means that `Task` could be removed and code refactored to use the functionally enhanced `Promise`.

---

@novemberborn commented on [Fri Aug 12 2016](https://github.com/dojo/core/issues/183#issuecomment-239416574)

The proposal adds new syntax so additional support from the TypeScript compiler may be required.

**Comment by kitsonk** [comment]
Related to #21

**Comment by kitsonk** [comment]
There is a [proper proposal](https://github.com/tc39/proposal-cancelable-promises) now, though it is still Stage 1.

**Comment by dylans** [comment]
Sadly the proposal was withdrawn due to internal disagreement at Google. So it sounds like we'll keep Task.
