### ISSUE TITLE
Use native Promise if available

### ISSUE THREAD

**Issue by novemberborn** [dojo/shim#21]
Unlike say `Map`, the `Promise` shim does not fall back to the native `Promise` if it's available. This means we're not benefiting from unhandled rejections and other promise debugging features in modern debuggers.

Currently the shim implements the non-standard `Promise#finally()`. This should be moved to `Task` before the native `Promise` can be used.

**Comment by kitsonk** [comment]
I really feel we need to address this before the beta release as it has several performance implications and potentially typing implications.

A another note, related to #16 is the [`Promise.prototype.finally`](https://github.com/tc39/proposal-promise-finally) is now a TC39 Stage 2 Proposal.

My thinking is that we should do the following:
- convert `dojo-shim/Promise` to a "full" shim like the rest of the shims
- migrate `.finally()` to `dojo-core/async/Task`
- polyfill those features back into `dojo-shim/Promise` when they reach Stage 4 (which for both is likely to be at least a year)
