### ISSUE TITLE
Behaviour when setting `.observeState()`

### ISSUE THREAD

**Issue by kitsonk** [dojo/shim#39]
Discussed between myself and @novemberborn in dojo/widgets#46 is that there is a potential _surprising_ behaviour when setting `.observeState()` in that if there was already an existing unobserved state, this would not necessarily get reflected in the source observed state.

For example, if I did the following:

``` typescript
import createMemoryStore from 'dojo-stores/createMemoryStore';
import createStateful from 'dojo-compose/mixins/createStateful';

const store = createMemoryStore({
    data: [ { id: 'foo', foo: 'bar' } ]
});

const stateful = createStateful({
    state: { bar: 2 }
});

stateful.observeState(store, 'foo');

console.log(stateful.state); // { id: 'foo', foo: 'bar', bar: 2 }
store.get('foo')
    .then((result) => console.log(result)); // { id: 'foo', foo: 'bar' }
```

Is this surprising?  What should be the correct behaviour?

**Comment by novemberborn** [comment]
I think the existing, unobserved state should be replaced. The question is whether `observeState()` should do that silently, or whether we need a separate `replaceState(store, id)` method. If there is a separate method then `observeState()` could be made to throw an exception if there is existing state.

---

@kitsonk is this issue in the right repo?

**Comment by matt-gadd** [comment]
closing as no longer relevant
