### ISSUE TITLE
WeakMap and deleting entries

### ISSUE THREAD

**Issue by kitsonk** [dojo/shim#6]
*\* Enhancement **

From a style perspective, when an instance is destroyed, we have often been cleaning up our WeakMap's by using `delete()` to remove the instance.  This isn't necessary because in even in the shim, the values of the WeakMap are set on a property of the object, therefore once all references to the object are out of scope, the object and it's WeakMap data will be freed up for GC.

@novemberborn pointed out that we should be consistent and therefore not delete WeakMap data unless there is a functional need, not during a destroy handle.  There are several instances of this in `dojo/widget` as well as other places.

**Comment by novemberborn** [comment]
I think the linked PRs cover all of them.

**Comment by kitsonk** [comment]
We have swept this through... closing.
