### ISSUE TITLE
Global cleanup

### ISSUE THREAD

**Issue by dylans** [dojo/shim#61]
Per https://github.com/dojo/shim/pull/56#issuecomment-263655382 :

* There's a global implementation in shim and a different one in dojo/core. Should the one in core be removed and usage of it replaced with this one?
* What happens with this global implementation is csp prevents unsafe eval?

**Comment by kitsonk** [comment]
The one in dojo/core should be removed.  Previously, there wasn't a "home" because it was non-standard.  Now that it is part of a formal proposal, it belongs in shim and should be removed from everywhere else.

**Comment by kitsonk** [comment]
Also, related to this, we should move it from `support/global.ts` to `global.ts` as it is aligned to the ES proposal.

**Comment by kitsonk** [comment]
As far as the second point, yes, that was the "old" way of doing global, and then in core we updated it with something that would work well with CSP, only to have missed it in support. 🤷‍♂️
