### ISSUE TITLE
ES import(specifier)

### ISSUE THREAD

**Issue by kitsonk** [dojo/shim#81]
**Enhancement** 

ECMAScript has a Stage 3 proposal for dynamic imports, using the syntax [`import(specifier)`](https://github.com/tc39/proposal-dynamic-import) which solves the challenges around dynamic non-top level imports in code.

There is some [work on TypeScript to support this](https://github.com/Microsoft/TypeScript/issues/14495) within TypeScript, but would still need a global "shim" to provide the functionality.  I think there are three things to consider:

- Identify any functionality gaps between the proposal and our requirements that might need to be continue to be provided (e.g. support AMD or Webpack loading)
- Provide the functionality as `dojo/shim/import` (though it will likely need to be global)
- Potentially modify/change the `dojo/loader` to expose `import()` as well as `require()` and `define()`?
- Deprecate `dojo/core/load` and migrate the webpack loader functionality into the shim.

**Comment by Jessidhia** [comment]
Note that, while `import` looks like a function, it is _not_ a function, and is actually impossible to implement as a function, which is why they had to make it a keyword to begin with. If you are going to provide something, it will need to either emulate one of the module APIs that TypeScript can already target, or a new target needs to be made.

**Comment by kitsonk** [comment]
@Kovensky fair point, it is a new [binding form](https://github.com/tc39/proposal-dynamic-import#a-new-binding-form) that isn't a function.  So maybe it is best to maintain `load` but potentially offload to`import(...)` when present in the native environment, or maybe just wait to see what happens with the TypeScript transpilation of `import(...)`.

**Comment by dylans** [comment]
We should probably close https://github.com/dojo/meta/issues/133 in favor of this one @kitsonk ?

**Comment by kitsonk** [comment]
We also need to keep an eye on Microsoft/TypeScript#14495 in relationship to this.  It may obviate us doing anything.

**Comment by dylans** [comment]
> We also need to keep an eye on Microsoft/TypeScript#14495 in relationship to this. It may obviate us doing anything.

Currently targeted for TS 2.3.1.

**Comment by kitsonk** [comment]
This has been implemented in TypeScript 2.4.1 and is considered syntax that is down emitted to ES5.  Therefore we have no need to implement this anymore.
