### ISSUE TITLE
Duplicate identifier 'Promise'

### ISSUE THREAD

**Issue by xblox** [dojo/shim#82]
Hi,
I am trying to adopt dojo-2 packages within a source-code layout using dojo-2 packages directly from source along with path mappings in my main's [tsconfig.json](https://github.com/xblox/dojo-experiments/blob/master/tsconfig.json#L15). I am pulling dojo-2 modules like git submodules with a home grown node util at their desired positions, placing your packages in a traditional layout: 

-src/lib/ 
-src/lib/shim
-src/lib/core
-src/lib/has
-src/lib/loader
-src/lib/stores
...

However,
I could manage to import stuff from shim, core, has and loader that way but when [I tried to import things from dojo/stores](https://github.com/xblox/dojo-experiments/blob/master/src/server.ts#L26) I get an `Duplicate identifier 'Promise'` error. 

I know its all in an early stage and I don't want to distract you from anything (feel free to close this here uncommented just) but if you could answer this here, I'd be more than happy (trying to write a starter dojo-2 blog post):

1. When using dojo-2 from source, the global identifier will be occupied by dojo's shimmed 'Promise', so I can't use the built-in native one anymore ? 

2. dojo-2 packages are not meant to be consumed from source directly? I am just asking this because it seems your exports are designed for a pre-built versions distribution only. That would be fatal for me since I can't and don't want to build my core on NPM's very limitations.

well, possibly I got it wrong again. 
Thanks already,
g

**Comment by kitsonk** [comment]
Right now, even though you want to build from source packages, you still have to use the npm infrastructure.  We are working on the Dojo 2 CLI tool that should help orchestrate this for you, including building your final bundle, but there is still development to do to make that all hang together.

For now, if you want to work with source packages, you still have to treat them as npm packages and use "linking" with npm.  For example, if you had a source version of `@dojo/shim` you wanted to use, in the source package for `shim` you would need to do a `grunt link`.  This will create a local link to the source package to be used by other packages.  Any time you then change the source code, you would use `grunt dist` to update the local distributable package.

Then in the package you want to consume that *custom* version of the package, you would use `npm link @dojo/shim` which would link to that local distribution.

This is essentially the workflow we use when needing to make co-dependent changes across packages before committing to the repo.  You can take a look at the `grunt link` task as well to see how we have to reshape the source package to something that can be easily consumed downstream.

**Comment by xblox** [comment]
thanks Kitson! Not sure how this will resolve the global collision of 'Promise' but I gonna give it a try. That sounds a like quite some stomach pain having npm/grunt/and some cli tool in the middle of my source code and the dojo-2 foundation code. Most of the time I do TS, I am using ts-node together with nodemon, on multiple source packages (works with my TS packages without any extra 'tricks'). I hope I can replicate this for dojo-2.

Even more headaches: the main reason why I knit dojo-2 packages along my own core packages is because I need dojo-2 packages to be build for the isomorphic scenario (commonjs/amd). Also, working directly with source code seems always a better fit to me since I can tune my main's tsconfig the way I need...

anyhow, thanks again!

**Comment by kitsonk** [comment]
> dojo-2 packages to be build for the isomorphic scenario

The distribution by default is UMD (compatible with CommonJS and AMD)...  So they are already built that way.  We experimented a lot with refactoring to have the module resolution work between NodeJS and in the browser with an AMD loader (with minimal configuration) and final built code based around WebPack (which is what `dojo build` works with).

The only thing we haven't really solved, yet, is embracing ESM and emitting ES6/ESNext target in TypeScript.  Right now, we are only confident in ES5 UMD emits.

As far as the duplicate of `Promise` it is really hard to say what is going on and likely has to do with configuration of the `tsconfig.json` and ASA (automatic type acquisition) with TypeScript.  When we follow the `grunt link` and `npm link package`, it helps sure that we only include the right types within the scope of the compiler for a project and generally don't run into that issue.

**Comment by xblox** [comment]
I see, thanks for the insights. gonna start digging into this next week again. I am ok with some detours since there isn't much offer to get proper std/foundation code in Typescript as seen in dojo-2 :-)

ps: I hope you guys keep isomorphic scenarios on the radar.

g
