### ISSUE TITLE
Run-time error: cannot assign to read only property 'raw' of object '[object Array]'

### ISSUE THREAD

**Issue by xblox** [dojo/shim#86]
Hi,
(close this here just if its caused by broken source code packages)

In my attempt to import dojo/core/Evented, I get a run-time error (tsc runs fine)
```
dojo-experiments/src/lib/has/src/has.ts:229
                result = testCache[normalizedFeature] = testFunctions[normalizedFeature].call(null);
                                                                           ^
TypeError: Cannot assign to read only property 'raw' of object '[object Array]'
    at /PMaster/projects/subs/dojo-experiments/src/lib/shim/src/support/has.ts:48:23
    at Object.has [as default] (/PMaster/projects/subs/dojo-experiments/src/lib/has/src/has.ts:229:76)
    at Object.<anonymous> (/PMaster/projects/subs/dojo-experiments/src/lib/shim/src/string.ts:253:92)
    at Module._compile (module.js:571:32)
    at Module.m._compile (/PMaster/projects/subs/dojo-experiments/node_modules/ts-node/src/index.ts:413:23)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/PMaster/projects/subs/dojo-experiments/node_modules/ts-node/src/index.ts:416:12)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

Same happens with dojo/stores parts or any other class/function which depends on dojo/shim. I [included](https://github.com/xblox/dojo-experiments/blob/master/tsconfig.json#L22) dojo-2 source code directly, using tsconfig with path mappings (pointing to dojo/package/src).

Is this caused by dojo-2's current design/progress, relying on UMD pre-builds and/or additional grunt/cli tasks and thus not being able to use dojo-2 source directly ? [Kitsonk mentioned] (https://github.com/dojo/shim/issues/82#issuecomment-285641657) something like this. If so, please close this here just if that goes away 'by-self' sometime; I can wait.

I tried to modify dojo/shim to 'fix' this but didn't succeed. 

[Here is an example project](https://github.com/xblox/dojo-experiments), demonstrating the issue.

**Comment by dylans** [comment]
@xblox this looks like it was closed before anyone replied, was that intentional?

**Comment by xblox** [comment]
@dylans: ups, just saw your comment now. I closed this because I am using dojo-2 by copying your source modules into my own core package for now: less hassle, true source code and less cli/tool stuff on the way. I am basically waiting for your ES6 'target' compatibility that way ;-)
g

**Comment by kitsonk** [comment]
Using the distributed packages with a downstream TypeScript project that targets ES2015+ should now be possible via #101 and is in release [v2.0.0-beta2.3](https://github.com/dojo/shim/releases/tag/v2.0.0-beta2.3).

**Comment by xblox** [comment]
@kitsonk : great, thanks! gonna try
